course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

enrollment/urls.py
from django.urls import path

from . import views

app_name = 'enrollment'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

lms/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("s/", include("student.urls")),
    path("c/", include("course.urls")),
    path("e/", include("enrollment.urls")),
    path('admin/', admin.site.urls),
]

student/urls.py
from django.urls import path

from . import views

app_name = 'student'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("signup/", views.sign_up, name="sign_up"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
]

course/models.py
from django.db import models

# Create your models here.

class Course(models.Model):
    title = models.CharField(max_length=191)
    description = models.TextField()
    instructor =  models.CharField(max_length=191)
    code = models.CharField(max_length=8)

    def __str__(self):
        return f"{self.title} ({self.instructor})"

enrollment/models.py
from django.db import models

from course.models import Course
from student.models import Student

# Create your models here.

class Enrollment(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    enrollment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student} ({self.course})"

relations/models.py
from django.db import models

# Many to many relation
class Publication(models.Model):
    title = models.CharField(max_length=30)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title

class Article(models.Model):
    headline = models.CharField(max_length=100)
    publications = models.ManyToManyField(Publication)

    class Meta:
        ordering = ["headline"]

    def __str__(self):
        return self.headline


# Many to one relation




# one to one relation

student/models.py
from django.db import models

# Create your models here.


class Student(models.Model):
    name = models.CharField(max_length=191)
    student_id = models.CharField(max_length=10)
    email = models.EmailField(max_length=254)

    def __str__(self):
        return f"{self.name} ({self.student_id}) <{self.email}>"

course/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views import generic

from .models import Course


class IndexView(generic.ListView):
    model = Course

    # # default -> course/course_list.html
    # template_name = "course/index.html"

    # # default -> "object_list"
    # context_object_name = "courses"

enrollment/views.py
from django.shortcuts import render
from django.http import HttpResponse

from django.views import generic

from .models import Enrollment


class IndexView(generic.ListView):
    model = Enrollment

    # # default -> enrollment/enrollment_list.html
    # template_name = "enrollment/index.html"

    # # default -> "object_list"
    # context_object_name = "enrollments"

relations/views.py
from django.shortcuts import render

# Create your views here.

student/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.views import generic

from .models import Student

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.core.paginator import Paginator


# @login_required(login_url=reverse_lazy('student:login'))
def index(request):
    if request.user.is_authenticated:
        students = Student.objects.all()
        paginator = Paginator(students, 5)  # Show 25 contacts per page.

        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        num_visits = request.session.get('num_visits', 0)
        request.session['num_visits'] = num_visits + 1

        return render(request, "student/student_list.html", {
            "object_list": students,
            "session": request.session,
            "page_obj": page_obj,
        })
    return redirect(reverse('student:login'))


class DetailView(LoginRequiredMixin, generic.DetailView):
    login_url = "/s/login/"
    context_object_name = "student"
    model = Student


def sign_up(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('student:index')) 
        return render(request, "student/student_signup.html")
    elif request.method == "POST":
        user = User.objects.create_user(
            username=request.POST.get('username'),
            email=request.POST.get('email'),
            password=request.POST.get('password'),
        )
        return HttpResponseRedirect(reverse('student:login')) 

def login_view(request):
    if request.method == "GET":
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('student:index')) 
        return render(request, "student/student_login.html")
    elif request.method == "POST":
        username = request.POST.get('username') # POST["username"]
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('student:index')) 
        else:
            return render(request, "student/student_login.html", {"login_message": "Username/password is incorrect"})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('student:login')) 

course/templates/course/course_list.html
{% extends "base.html" %}

{% block title_block %} Course list {% endblock title_block %}

{% block body_block %}
<header style="padding: 10px 20px; background-color: blue;">
    <nav>
        <div>KS LMS</div>
        <a href={% url "student:logout" %} > Logout </a>
    </nav>
</header>

<ul>
    {% for object in object_list %}
        <li>{{ object.code }} ({{ object.title }}) &lt;{{ object.instructor }}&gt;</li>
    {% endfor %}
</ul>
{% endblock body_block %}

    

enrollment/templates/enrollment/enrollment_list.html
<ul>
    {% for object in object_list %}
        <li>{{ object.course.code }} ({{ object.student.student_id }}) &lt;{{ object.enrollment_date }}&gt;</li>
    {% endfor %}
</ul>
    

student/templates/student/partials/header.html
<header>
    <nav>
        <a href={% url "student:index" %}><div>KS LMS</div> </a>
        <a href={% url "student:logout" %} > Logout </a>
    </nav>
</header>

student/templates/student/student_detail.html
{% extends "base.html" %}
{% load static %}

{% block links_block %}
    <link rel="stylesheet" href={% static "student/style.css" %}>
{% endblock links_block %}

{% block title_block %} {{student.name}} Details {% endblock title_block %}

{% block body_block %}
    {% include "student/partials/header.html" %}
    <h1> {{student.name}} </h1>
    <h2> Student ID: {{student.student_id}} </h2>
    <h3> Email: {{student.email}} </h3>
    <ul>
        {% for enrollment in student.enrollment_set.all %}
            <li> {{enrollment.course.title}} </li>
        {% endfor %}
    </ul>
{% endblock body_block %}

student/templates/student/student_list.html
{% extends "base.html" %}
{% load static %}

{% block links_block %}
    <link rel="stylesheet" href={% static "student/style.css" %}>
{% endblock links_block %}
{% block title_block %} Students list {% endblock title_block %}

{% block body_block %}
{% include "student/partials/header.html" %}
    <main>
        <ul>
        {% for object in page_obj %}
            <li class="{% cycle 'one' 'two' 'three' 'four' %}">
                <a href={% url "student:detail" object.id %}>
                    {{ object.name|title }}
                </a>
            </li>
        {% endfor %}
        </ul>
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
        
                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
        {% comment %} {% for key, value in session.items %}
            {{key}}: {{value}} <br/>
        {% endfor %} {% endcomment %}
    </main>

    <footer>
        <nav>
            <p>@Copyright KS.tech</p>
        </nav>
    </footer>
{% endblock body_block %}

student/templates/student/student_login.html
{% extends "base.html" %}
{% load static %}

{% block links_block %}
    <link rel="stylesheet" href={% static "student/style.css" %}>
{% endblock links_block %}
{% block title_block %} Student login {% endblock title_block %}

{% block body_block %}
{% include "student/partials/header.html" %}
<h1> Login </h1>
<form action="{% url 'student:login' %}" method="post">
    {% csrf_token %}
    {% if login_message %}<p style="color: red"><strong>{{ login_message }}</strong></p>{% endif %}
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="email">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Login" id="login">
</form>

<a href="{% url 'student:sign_up' %}"> Sign up </a>
{% endblock body_block %}

student/templates/student/student_signup.html
{% extends "base.html" %}
{% load static %}

{% block links_block %}
    <link rel="stylesheet" href={% static "student/style.css" %}>
{% endblock links_block %}
{% block title_block %} Student Signup {% endblock title_block %}

{% block body_block %}
{% include "student/partials/header.html" %}
<h1> Register </h1>
<form action="{% url 'student:sign_up' %}" method="post">
    {% csrf_token %}
    {% if register_message %}<p style="color: red"><strong>{{ register_message }}</strong></p>{% endif %}
    <label for="fname">First name: </label>
    <input type="text" value="" name="fname"> <br/><br/>
    <label for="lname">Last Name: </label>
    <input type="text" value="" name="lname"> <br/><br/>
    <label for="email">Email: </label>
    <input type="email" value="" name="email"> <br/><br/>
    <label for="username">Username: </label>
    <input type="text" value="" name="username"> <br/><br/>
    <label for="password">Password: </label>
    <input type="password" value="" name="password"> <br/><br/>
    <input type="submit" value="Register" id="register">
</form>

<a href="{% url 'student:login' %}"> Login </a>
{% endblock body_block %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title_block %} Empty Title {% endblock title_block %}</title>

    {% block links_block %}{% endblock links_block %}
</head>
<body>
    {% block body_block %} Empty Body {% endblock body_block %}
</body>
</html>